### PR TITLE
Add more inputs for DENON

### PR DESCRIPTION
**Pull request by moifort**
Need IRP input to run directly the selected Internet Radio on my DENON

### CODE REVIEW

**Comment by luc-ass** [comment]
sounds good. how stable is ist? how long have you been running it?

**Comment by moifort** [comment]
Look good for me, it's running for me since 3 days. 

I add other input according to the documentation: http://openrb.com/wp-content/uploads/2012/02/AVR3312CI_AVR3312_PROTOCOL_V7.6.0.pdf 

Thibaut.

**Comment by moifort** [comment]
I upgrade the version to `0.2.1` so you can publish it on npm.

**Comment by stfnhmplr** [comment]
works fine. thanks 👍

**Pull request merged**
