### PR TITLE
switching to telnet and added support for the second zone

### PR DESCRIPTION
**Pull request by stfnhmplr**
- complete rewrite
- support speaker service (volume control with eve app) #16
- added support for second zone #19 
- switched to telnet connection to support the newer avr's #22 #23 
- removed default input and default volume

### CODE REVIEW

**Comment by luc-ass** [comment]
I will happily review your code in the following days. How long has it been running at your place?

**Comment by stfnhmplr** [comment]
Since a few days. Did you tried it yet?

**Comment by vqv** [comment]
I just installed a test the dev branch briefly with my Denon AVR-X3400H.  In the Eve app I see two volume controls and two power switches: one pair for main and one pair for 2nd zone.  I do not have a 2nd zone physically connected, but control of volume works for the main zone.  I do not see input switching exposed anywhere.  Is there a configuration option or is this absent from the plugin?

**Edit** Some more observations:

- Mute works.
- The plugin does not seem to be polling or something is wrong with it. If I power off the receiver, homebridge does not reflect this.

**Comment by NickChristensen** [comment]
I could help with this feature after this is merged and released, but it would be nice to make the second zone optional via configuration.

**Comment by stfnhmplr** [comment]
@vqv Thanks for testing. The selection of inputs will only be possible with the next version. I will adapt it to the new iOS version and removed the default input option for now.
Since the connection is established via Telnet, polling is no longer necessary. The receiver now reports a change back to the plugin via the Telnet connection. I just tried this again and it works for me. But I still added two more commands, maybe the receivers report the state in a different way.

@NickChristensen Thanks. That makes sense. The second Zone is now optional.

I think I will merge this PR tomorrow.

**Pull request merged**
